apiVersion: v1
kind: Service
metadata:
  name: beacon-chain
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: beacon-chain
  ports:
    - name: grpc-port
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: http-port
      protocol: TCP
      port: 3500
      targetPort: 3500
    - name: api-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: pprof-port
      protocol: TCP
      port: 6060
      targetPort: 6060
    - name: metrics-port
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
