apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      serviceAccountName: kubectl-sa
      initContainers:
      - name: wait-for-geth-genesis
        image: "{{ .Values.image.kubectlImage }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for geth-genesis Job to complete..."
            until kubectl get job geth-genesis -n {{ .Release.Namespace }} -o jsonpath='{.status.succeeded}' | grep "1"; do
              echo "Job not completed yet. Checking again in 10 seconds..."
              sleep 10
            done
            echo "geth-genesis Job completed successfully."
      containers:
      - name: geth
        image: "{{ .Values.image.geth }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
          - --http
          - --http.api=eth,net,web3
          - --http.addr=0.0.0.0
          - --http.corsdomain=*
          - --ws
          - --ws.api=eth,net,web3
          - --ws.addr=0.0.0.0
          - --ws.origins=*
          - --authrpc.vhosts=*
          - --authrpc.addr=0.0.0.0
          - --authrpc.jwtsecret={{ .Values.volumes.execution }}/jwtsecret
          - --datadir={{ .Values.volumes.execution }}
          - --allow-insecure-unlock
          - --unlock=0x1d6197196c227e2be52c917b62343f7815638b2d
          - --password={{ .Values.volumes.execution }}/geth_password.txt
          - --nodiscover
          - --syncmode=full
        ports:
        {{- range .Values.ports.geth }}
        - containerPort: {{ . }}
        {{- end }}
        volumeMounts:
          - name: execution
            mountPath: {{ .Values.volumes.execution }}
          - name: jwtsecret-volume
            mountPath: {{ .Values.volumes.execution }}/jwtsecret
            subPath: jwtsecret
          - name: geth-password-volume
            mountPath: {{ .Values.volumes.execution }}/geth_password.txt
            subPath: geth_password.txt
        env:
        - name: GETH_PORT
          value: "80"
      volumes:
      - name: execution
        hostPath:
          path: {{ .Values.volumes.localexecution }}
      - name: jwtsecret-volume
        secret:
          secretName: jwtsecret
      - name: geth-password-volume
        secret:
          secretName: geth-password
      nodeSelector:
        kubernetes.io/arch: amd64 
