apiVersion: v1
kind: Service
metadata:
  name: geth
  namespace: default  # Change if necessary
spec:
  selector:
    app: geth
  ports:
    - name: rpc-port
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: ws-port
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: authrpc-port
      protocol: TCP
      port: 8551
      targetPort: 8551
  type: ClusterIP
