apiVersion: v1
kind: Secret
metadata:
  name: jwtsecret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwtsecret: MHhmYWQyNzA5ZDBiYjAzYmYwZThiYTNjOTliZWExOTQ1NzVkM2U5ODg2MzEzM2QxYWY2MzhlZDA1NmQxZDU5MzQ1