apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-jobs
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: kubectl-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
